name: Docker CI - php/8.3

on:
  push:
    branches: ['main']
    paths:
      - 'php/8.3/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./php/8.3
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dev-environments/php/8.3:latest
